[SELC-4198] Feat: remove relationship id from api parameters
pagopa/selfcare-dashboard-users-microfrontend pull request #370
Opened 2024-03-04 16:37 UTC by OraldoDoci

#### List of Changes
Change parameters of api suspend, activate and delete that handles users roles

#### Motivation and Context
In order to substitute relatioshipid with triples userId product id institution id 

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-04 16:49 UTC, loremedda commented
OK

2024-03-05 08:43 UTC, loremedda commented
Why handle it with a hard-coded boolean? Potentially, this branch can remain stationary and block other implementations....
If it remains stopped for some time, once this branch is resumed, there may be some inconvenient dependencies to resolve

2024-03-05 08:44 UTC, loremedda requested changes
Why handle it with a hard-coded boolean? Potentially, this branch can remain stationary and block other implementations....
If it remains stopped for some time, once this branch is resumed, there may be some inconvenient dependencies to resolve

2024-03-05 15:13 UTC, gianmarcoplutino approved these changes

2024-03-05 15:14 UTC, merged